server:
  port: 8300
spring:
  application:
    name: hl-zuul
eureka:
  client:
    service-url:
      # eureka的服务端地址
      defaultZone: http://127.0.0.1:8100/eureka/
zuul:
  routes:
    # 指定路由前缀，名称任意唯一
    school:
      # 网关路由的服务名称
      serviceId: hl-school-service
      # 指定请求中使用的路径，最后会将/school/** 替换成 /hl-school-service
      path: /school/**
  ignored-services: "*"
