server:
  port: 8102

spring:
  application:
    name: hl-eureka-server-2

eureka:
  instance:
    # eureka集群配置必须使用域名，否则会出现unavailable-replicas
    hostname: eureka-8102.com
    instance-id: eureka-8102
  client:
    service-url:
      defaultZone: http://eureka-8101.com:8101/eureka/
    register-with-eureka: true
    fetch-registry: true
