server:
  port: 8100
spring:
  application:
    name: hl-eureka-server-simple
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 是否注册自己到eureka server
    register-with-eureka: false
    # 是否扫描其他eureka server
    fetch-registry: false