server:
  port: 8300
spring:
  application:
    name: hl-zuul
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defalutZone: http://${eureka.instance.hostname}:8100/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
