server:
  port: 8200

spring:
  application:
    name: hl-zipkin-server

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/