debug: true
server:
  port: 8101
spring:
  application:
    name: hl-eureka-server-1
eureka:
  instance:
    # eureka集群配置必须使用域名，否则会出现unavailable-replicas
    hostname: eureka-8101.com
    instance-id: eureka-8101
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka/,http://127.0.0.1:8102/eureka/
